### PR TITLE
fix(yaml) Allow specifying file path as an URL

### LINKED ISSUE #357: [yaml] error when the "file" key is an URL
**Describe the bug**

As per the documentation (https://www.updatecli.io/docs/resources/yaml/#_file) the attribute `file` of YAML resource can be either a file path, or an "URL"-like (with a prefix scheme).

But the URL-like values are resulting on errors, at least on a YAML source.

**To Reproduce**

The following snippet fails when for both `file://` and `https://` URL schemes:

```yaml
---
title: Show a set of yaml resources as a generic example
sources:
  default:
    kind: yaml
    spec:
      file: examples/values.yaml
      key: "github.user"
  fromExplicitFile:
    kind: yaml
    spec:
      file: file://examples/values.yaml
      key: "github.user"
  fromUrl:
    kind: yaml
    spec:
      file: https://raw.githubusercontent.com/updatecli/updatecli/dc90759914718beee17101c693911088cfbf6deb/examples/values.yaml
      key: "github.user"
```

```shell
#####################################################
# SHOW A SET OF YAML RESOURCES AS A GENERIC EXAMPLE #
#####################################################


SOURCES
=======

fromUrl
-------
ERROR: ✗ open /Users/dadou/workspace/updatecli/updatecli/https:/raw.githubusercontent.com/updatecli/updatecli/dc90759914718beee17101c693911088cfbf6deb/examples/values.yaml: no such file or directory

fromExplicitFile
----------------
ERROR: ✗ open /Users/dadou/workspace/updatecli/updatecli/file:/examples/values.yaml: no such file or directory

default
-------
✔ Value 'olblak' found for key github.user in the yaml file examples/values.yaml
```

**Expected behavior**

- I would expect the case with `file://` to work as expected (e.g. the scheme prefix should be removed)
- For the URL like, I'm not sure if it should be supported, or not. WDYT @olblak ?

**Screenshots**
N.A.

**Version (please complete the following information):**
 - OS: macOS
 - Version 0.13.1

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by dduportal**
Fix #357 

This PRs allow specifying Yaml file path as URLs.

## Test
To test this pull request, you can run the following commands:

```
go build -o ./dist/updatecli && ./dist/updatecli diff --config ./examples/updateCli.generic/yaml.yaml
```

## Additional Information

- Introduced a `New` method to create a Yaml object
- Separate `YamlSpec` from `Yaml` objects to allow injection for unit testing/mocking + easier feature upgrades
- Use the same strategy as the file resource by adding a `Read()` method
- Updated examples to provide more cases

### CODE REVIEW

File: pkg/plugins/yaml/main.go [hunk 1]
```diff
@@ -15,13 +18,61 @@ var (
...
+	File string
+	Key  string
+	// Deprecated: use File instead
 	Path  string
 	Value string
 }
 
+// Yaml defines a resource of type "yaml"
+type Yaml struct {
+	Spec             YamlSpec
```
Comment (olblak) [inline pkg/plugins/yaml/main.go:31]: Any reason to make public Spec instead of spec?

**Review by olblak — APPROVED** [review]
Thank you for the cleanup, excepted a  minor question, everything look good to me

File: pkg/plugins/yaml/main.go (hunk 1 above)
Comment (dduportal) [reply pkg/plugins/yaml/main.go:31]: Because of the resource of type `helm` which uses the `Yaml` types, as you can see in this change (diff of the current PR): https://github.com/updatecli/updatecli/pull/360/files#diff-beb8c6d04ce8efe2a8e014a3137114c2d8e1f9dd850ed2d5df13e40e3f685446R36

I chose to not work on decoupling both (like with `text`  / `file` `yaml`) in the context of this PR since it's a bug fix (and not a feature).

If it's ok for you, after fixing this bug,  #358 and #359 , I would like to factorize the logging logic of the yaml module (as in #354 for shell) , that would be a perfect spot for decoupling.

**Comment by dduportal** [comment]
@olblak if the proposal is ok for you, can I let you approve and merge?
