### PR TITLE
fix: Gitea pullrequest shouldn't try to be opened if missing remote branches

### LINKED ISSUE #867: Updatecli fails if no Gitea Pullrequest need to be created
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updatecli fails if no Gitea Pullrequest need to be created

```
TARGETS
========

ueadme
------
✔ Content from file "/tmp/updatecli/gitea/olblak/updatecli-test/README.md" already up to date
✔ All contents from 'file' and 'files' combined already up to date


PULL REQUESTS
=============

Pipeline "Test Gitea tag" failed
Skipping due to:
	pull Request stage:	"Not Found"

=============================
```

### Expected Behavior

I wouldn't expect Updatecli to fail if something has to be changed

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:Linux
- updatecli: 0.33.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by olblak**
Fix #867 

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

### CODE REVIEW

File: pkg/plugins/resources/gitea/pullrequest/create_test.go [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+			name: "pullrequest shouldn't be created on olblak/updatecli should not exist",
+			manifest: struct {
+				URL          string
+				Token        string
+				Owner        string
+				Repository   string
+				SourceBranch string
+				TargetBranch string
+			}{
+				URL:          "try.gitea.io",
```
Comment (lafriks) [inline pkg/plugins/resources/gitea/pullrequest/create_test.go:40]: try.gitea.io should not be used for tests as it's not guaranteed to be working at all times or even preserve repositories there. Please use something more stable like codeberg.org

Comment (olblak) [reply pkg/plugins/resources/gitea/pullrequest/create_test.go:40]: Thanks for the feedback, `try.gitea.io` was a "temporary" solution until I find a better solution and then I discovered codeberg.org

I recently created an account over ther and now I have to migrate the tests
