### PR TITLE
fix: GitHub pullrequest description updated to a wrong content 

### LINKED ISSUE #2068: GitHub pullrequest description updated to a wrong content
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From time to time, Updatecli updates a pullrequest description to something totally unrelated and then can restore it back. 

image

### Expected Behavior

The pullrequest should always represents the content of the pullrequest.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:linux
- updatecli: v0.76.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by olblak**
Fix #2068 

## Test

To test this pull request, you can run the following commands:

```shell
cd <to_package_directory>
go test
```

### CODE REVIEW

File: pkg/core/pipeline/actions.go [hunk 1]
```diff
@@ -54,40 +45,39 @@ func (p *Pipeline) RunActions(pipelineState string) error {
...
-			when two different pipeline open the same pullrequest based on the same action title
-		*/
+		// Ignoring failed targets
+		if len(failedTargetIDs) > 0 {
+			logrus.Errorf("%d target(s) (%s) failed for action %q", len(failedTargetIDs), strings.Join(failedTargetIDs, ","), id)
+		}
+
+		// Ignoring skipped targets
+		if len(skippedTargetIDs) > 0 {
+			logrus.Warningf("%d target(s) (%s) skipped for action %q", len(skippedTargetIDs), strings.Join(skippedTargetIDs, ","), id)
```
Comment (olblak) [inline pkg/core/pipeline/actions.go:61]:
```suggestion
			logrus.Debugf("%d target(s) (%s) skipped for action %q", len(skippedTargetIDs), strings.Join(skippedTargetIDs, ","), id)
```
