### PR TITLE
fix: propagate npmrcpath to lockfile shell targets

### LINKED ISSUE #7670: npm autodiscovery: propagate npmrcpath to shell targets for lock file updates
## Problem

`npmrcpath` is propagated to the npm **source** resource spec (for registry queries) but not to the shell **target** commands that run `npm install` / `yarn add` / `pnpm add` for lock file updates.

When a private registry requires authentication, the source can fetch package metadata but the lock file update fails with `E401 Unauthorized` because the npm CLI doesn't know about the custom `.npmrc` path.

## Expected

The generated shell target should pass `npmrcpath` to the npm CLI, either via:
- `NPM_CONFIG_USERCONFIG` environment variable in the shell spec's `environments`, or
- `--userconfig` flag on the generated command

## Ref

Follow-up to #7478 / PR #7479 which added `npmrcpath` propagation at the source level.

### PR DESCRIPTION
**Pull request by nickzerjeski**
Fix #7670

Propagate `npmrcpath` to generated shell targets for lockfile updates by adding `NPM_CONFIG_USERCONFIG` to target environments when `npmrcpath` is configured.

## Test

To test this pull request, you can run the following commands:

```shell
cd pkg/plugins/autodiscovery/npm
go test -run 'TestNew_WithResourceConfig|TestDiscoverManifests_WithResourceConfig'
```

### Checklist

- [ ] I have updated the documentation via pull request in [website](https://github.com/updatecli/website) repository.

### Tradeoff

- The environment variable is injected in shell targets only when `npmrcpath` is set, so manifests without `npmrcpath` are unchanged.

### Potential improvement

- Extend the test matrix with a hermetic pnpm/yarn command mock so full `TestDiscoverManifests` can assert all lockfile target variants without local tool dependencies.

### CODE REVIEW

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go [hunk 1]
```diff
@@ -85,6 +89,10 @@ targets:
             - "package.json"
       environments:
        - name: PATH
+{{- if .SourceNpmrcPath }}
+       - name: NPM_CONFIG_USERCONFIG
+         value: '{{ .SourceNpmrcPath }}'
+{{- end }}
```
[the remark this answers is not in the document]
Comment (nickzerjeski) [reply pkg/plugins/autodiscovery/npm/manifestTemplate.go]: @copilot apply changes based on [this feedback](https://github.com/updatecli/updatecli/pull/8407#discussion_r3071898228)

File: pkg/plugins/autodiscovery/npm/main_test.go [hunk 2]
```diff
@@ -289,4 +289,6 @@ func TestDiscoverManifests_WithResourceConfig(t *testing.T) {
 	assert.Contains(t, manifestStr, "npmrcpath: '/custom/.npmrc'")
 	assert.Contains(t, manifestStr, "url: 'https://npm.example.com'")
 	assert.Contains(t, manifestStr, "registrytoken: 'test-token-123'")
+	assert.Contains(t, manifestStr, "- name: NPM_CONFIG_USERCONFIG")
+	assert.Contains(t, manifestStr, "value: '/custom/.npmrc'")
```
[the remark this answers is not in the document]
Comment (nickzerjeski) [reply pkg/plugins/autodiscovery/npm/main_test.go:294]: @copilot apply changes based on [this feedback](https://github.com/updatecli/updatecli/pull/8407#discussion_r3071898208)

**Comment by nickzerjeski** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/updatecli/updatecli/pull/8407#pullrequestreview-4097526701)

**Comment by olblak** [comment]
Thank you for the pullrequest.
I'll try to find some time to review it

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go [hunk 3]
```diff
@@ -59,7 +59,9 @@ targets:
             - "package-lock.json"
             - "package.json"
       environments:
-       - name: PATH
+        - name: PATH{{ if .SourceNpmrcPath }}
+        - name: NPM_CONFIG_USERCONFIG
+          value: '{{ .SourceNpmrcPath }}'{{ end }}
```
Comment (loispostula) [inline pkg/plugins/autodiscovery/npm/manifestTemplate.go]: We tend to use this formatting
```suggestion
        - name: PATH
        {{- if .SourceNpmrcPath }}
        - name: NPM_CONFIG_USERCONFIG
          value: '{{ .SourceNpmrcPath }}'
        {{ end }}
```

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go [hunk 4]
```diff
@@ -84,7 +86,9 @@ targets:
             - "yarn.lock"
             - "package.json"
       environments:
-       - name: PATH
+        - name: PATH{{ if .SourceNpmrcPath }}
+        - name: NPM_CONFIG_USERCONFIG
+          value: '{{ .SourceNpmrcPath }}'{{ end }}
```
Comment (loispostula) [inline pkg/plugins/autodiscovery/npm/manifestTemplate.go]: See https://github.com/updatecli/updatecli/pull/8407/changes#r3081829404

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go [hunk 5]
```diff
@@ -109,7 +113,9 @@ targets:
             - "pnpm-lock.yaml"
             - "package.json"
       environments:
-       - name: PATH
+        - name: PATH{{ if .SourceNpmrcPath }}
+        - name: NPM_CONFIG_USERCONFIG
+          value: '{{ .SourceNpmrcPath }}'{{ end }}
```
Comment (loispostula) [inline pkg/plugins/autodiscovery/npm/manifestTemplate.go]: See https://github.com/updatecli/updatecli/pull/8407/changes#r3081829404

**Review by loispostula — DISMISSED** [review]
Few formatting nit, otherwise looks good! Thanks

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go (hunk 3 above)
Comment (nickzerjeski) [reply pkg/plugins/autodiscovery/npm/manifestTemplate.go]: Done in commit f921f850. Updated formatting to match project style for this environment block (`PATH` on its own line, then conditional `NPM_CONFIG_USERCONFIG` block) and applied the same pattern consistently across all lockfile shell targets.

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go (hunk 4 above)
Comment (nickzerjeski) [reply pkg/plugins/autodiscovery/npm/manifestTemplate.go]: Applied the same formatting in this block as well in commit f921f850 (matching the reference style from r3081829404).

File: pkg/plugins/autodiscovery/npm/manifestTemplate.go (hunk 5 above)
Comment (nickzerjeski) [reply pkg/plugins/autodiscovery/npm/manifestTemplate.go]: Applied here too in commit f921f850. All three target blocks now use the same requested formatting.

**Review by olblak — APPROVED** [review]
