### PR TITLE
fix(temurin) fail explicitly when specifying condition or target of kind 'temurin'

### LINKED ISSUE #2839: The Adoptium API has changed the location header
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the debug mode, I can see `DEBUG: [temurin] API client got the following Location header value: "".`
It makes me think of the [discussion](https://adoptium.slack.com/archives/C09NLQQAV/p1728223668491699?thread_ts=1728128855.456059&cid=C09NLQQAV) Mark Waite and the Temurin team got about the recent changes due to the CloudFlare usage.

```
CONDITIONS:
===========

checkTemurinAlpineRelease
-------------------------
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/architectures"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[8d365b2e7bd299d9-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 16 Oct 2024 07:32:38 GMT] Server:[cloudflare] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-f6979b64b-zgv68]] 0xc00126c2a0 -1 [] false true map[] 0xc001034c80 0xc0011f20c0}
DEBUG: [temurin] API client got the following Location header value: "".
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/operating_systems"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[8d365b2f3c6d99d9-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 16 Oct 2024 07:32:39 GMT] Server:[cloudflare] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-f6979b64b-zgv68]] 0xc0010c2fc0 -1 [] false true map[] 0xc001034f00 0xc0011f20c0}
DEBUG: [temurin] API client got the following Location header value: "".
✗
```

### Expected Behavior

Not such a warning.

### Steps To Reproduce

1. Clone https://github.com/gounthar/docker.git
2. Checkout the `adoptium-source` branch
3. `updatecli diff --debug --config ./updatecli/updatecli.d/jdk21.yaml --values ./updatecli/values.github-action.yaml 2>&1`

### Environment

```markdown
- OS: WSL2/Debian
- updatecli: 0.85.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dduportal**
Fix #2839

This PR ensures that any run with a manifest using conditions or targets of type `temurin` are failing with an explicit message for the end user.

Running this PR with the manifest at https://github.com/gounthar/docker/blob/2353803ff5fad52db4b48429ddc394414f98bfa6/updatecli/updatecli.d/jdk21.yaml ends with the following message:

```
condition: condition#checkTemurinAlpineRelease
-----------------------------------

ERROR: something went wrong in "condition#checkTemurinAlpineRelease" : Condition not supported for the resources of kind 'temurin'

Pipeline "Bump JDK21 version" failed
Skipping due to:
        something went wrong during target execution
```

## Test

To test this pull request, you can run the following commands:

```shell
cd pkg/plugins/resources/temurin
go test
```

### Potential improvement

In the future we could implement conditions of type temurin. See https://github.com/updatecli/updatecli/issues/2915

### CODE REVIEW

File: pkg/plugins/resources/temurin/condition.go [hunk 1]
```diff
@@ -9,5 +11,6 @@ Condition tests if the response of the specified HTTP request meets assertion.
 If no assertion is specified, it only checks for successful HTTP response code (HTTP/1xx, HTTP/2xx or HTTP/3xx).
 */
 func (t *Temurin) Condition(source string, scm scm.ScmHandler) (pass bool, message string, err error) {
-	return false, "", nil
+	message = "Condition not supported for the resources of kind 'temurin'"
```
Comment (olblak) [inline pkg/plugins/resources/temurin/condition.go:14]:
```suggestion
	message = "Condition not supported for the resource of kind 'temurin'"
```

File: pkg/plugins/resources/temurin/target.go [hunk 2]
```diff
@@ -1,11 +1,13 @@
...
+	"fmt"
+
 	"github.com/updatecli/updatecli/pkg/core/pipeline/scm"
 	"github.com/updatecli/updatecli/pkg/core/result"
 )
 
 // Target is not implemented. If you ever feel the need, you can still open a GitHub issue with a valid usecase.
 func (t *Temurin) Target(source string, scm scm.ScmHandler, dryRun bool, resultTarget *result.Target) error {
-	return nil
+	return fmt.Errorf("Target not supported for the resources of kind 'temurin'")
```
Comment (olblak) [inline pkg/plugins/resources/temurin/target.go:12]:
```suggestion
	return fmt.Errorf("Target not supported for resource of kind 'temurin'")
```

File: pkg/plugins/resources/temurin/condition.go [hunk 3]
```diff
@@ -9,5 +11,6 @@ Condition tests if the response of the specified HTTP request meets assertion.
 If no assertion is specified, it only checks for successful HTTP response code (HTTP/1xx, HTTP/2xx or HTTP/3xx).
 */
 func (t *Temurin) Condition(source string, scm scm.ScmHandler) (pass bool, message string, err error) {
-	return false, "", nil
+	message = "Condition not supported for the resource of kind 'temurin'"
```
Comment (olblak) [inline pkg/plugins/resources/temurin/condition.go:14]:
```suggestion
	message = "Condition not supported for resource of kind 'temurin'"
```

**Review by olblak — APPROVED** [review]
