### PR TITLE
fix: handle non-existing cargo packages

### LINKED ISSUE #1459: cargopackage: Conditions error on non existing package
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, if using condition with `kind: cargopackage` for a non existing package, the condition errors. 

### Expected Behavior

When the package does not exist the condition should not errored.

### Steps To Reproduce

Given the following config:
```yaml
name: Retrieve the latest Cargo Package Version

scms:
  private-registry:
    kind: git
    spec:
      url: "https://github.com/updatecli-test/fake-cargo-registry.git"
      branch: "main"

conditions:
  existing-package-private-reg:
    name: Test if test-crate-2 0.1.0 exists on private registry
    kind: cargopackage
    scmid: private-registry
    spec:
      package: test-crate-2
      version: 0.1.0
  existing-package-not-existing-version-private-reg:
    name: Test if test-crate-2 0.6.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: test-crate-2
      version: 0.6.0
  non-existing-package-private-reg:
    name: Test if non-existing-test-crate 0.1.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: non-existing-test-crate
      version: 0.1.0
  existing-package-public-reg:
    name: Test if rand version exists on public reg
    kind: cargopackage
    spec:
      package: rand
      version: 0.7.2
  existing-package-p-not-existing-version-public-reg:
    name: Test if rand version 99.99.99 does not exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: rand
      version: 99.99.99
  non-existing-package-public-reg:
    name: Test if non-existing-package-to-be-sure-123456 does exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: non-existing-package-to-be-sure-123456
      version: 0.7.2
```

All condition should be met. But this errors

### Environment

```markdown
- OS:
- updatecli:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by loispostula**
Fix #1459

Make sure we can handle the cases when a package does not exists

## Test

To test this pull request, you can run check the following pipeline file
```yaml
name: Retrieve the latest Cargo Package Version

scms:
  private-registry:
    kind: git
    spec:
      url: "https://github.com/updatecli-test/fake-cargo-registry.git"
      branch: "main"

conditions:
  existing-package-private-reg:
    name: Test if test-crate-2 0.1.0 exists on private registry
    kind: cargopackage
    scmid: private-registry
    spec:
      package: test-crate-2
      version: 0.1.0
  existing-package-not-existing-version-private-reg:
    name: Test if test-crate-2 0.6.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: test-crate-2
      version: 0.6.0
  non-existing-package-private-reg:
    name: Test if non-existing-test-crate 0.1.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: non-existing-test-crate
      version: 0.1.0
  existing-package-public-reg:
    name: Test if rand version exists on public reg
    kind: cargopackage
    spec:
      package: rand
      version: 0.7.2
  existing-package-p-not-existing-version-public-reg:
    name: Test if rand version 99.99.99 does not exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: rand
      version: 99.99.99
  non-existing-package-public-reg:
    name: Test if non-existing-package-to-be-sure-123456 does exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: non-existing-package-to-be-sure-123456
      version: 0.7.2
```

### CODE REVIEW

**Review by olblak — APPROVED** [review]

File: pkg/plugins/resources/cargopackage/condition_test.go [hunk 1]
```diff
@@ -61,6 +61,18 @@ func TestCondition(t *testing.T) {
 			expectedResult: true,
 			expectedError:  false,
 		},
+		{
+			name: "Retrieving non existing not-crate-test from the filesystem index",
```
Comment (olblak) [inline pkg/plugins/resources/cargopackage/condition_test.go:65]:
```suggestion
			name: "Retrieving none existing not-crate-test from the filesystem index",
```

File: pkg/plugins/resources/cargopackage/condition_test.go [hunk 2]
```diff
@@ -129,6 +141,28 @@ func TestCondition(t *testing.T) {
 			mockedHeaderFormat:   "Bearer %s",
 			mockedHTTPStatusCode: existingPackageStatus,
 		},
+		{
+			name: "Retrieving non-existing non-crate-test from the mocked private registry",
```
Comment (olblak) [inline pkg/plugins/resources/cargopackage/condition_test.go:145]:
```suggestion
			name: "Retrieving none existing non-crate-test from the mocked private registry",
```

File: pkg/plugins/resources/cargopackage/source_test.go [hunk 3]
```diff
@@ -58,6 +58,20 @@ func TestSource(t *testing.T) {
 			expectedResult: "0.1.0",
 			expectedError:  false,
 		},
+		{
+			name: "Passing case of retrieving non-existing crate-test from the filesystem index",
```
Comment (olblak) [inline pkg/plugins/resources/cargopackage/source_test.go:62]:
```suggestion
			name: "Passing case of retrieving none existing crate-test from the filesystem index",
```

File: pkg/plugins/resources/cargopackage/condition_test.go [hunk 4]
```diff
@@ -61,6 +61,18 @@ func TestCondition(t *testing.T) {
 			expectedResult: true,
 			expectedError:  false,
 		},
+		{
+			name: "Retrieving none existing not-crate-test from the filesystem index",
```
Comment (lemeurherve) [inline pkg/plugins/resources/cargopackage/condition_test.go:65]:
```suggestion
			name: "Retrieving non existing not-crate-test from the filesystem index",
```

File: pkg/plugins/resources/cargopackage/condition_test.go [hunk 5]
```diff
@@ -129,6 +141,28 @@ func TestCondition(t *testing.T) {
 			mockedHeaderFormat:   "Bearer %s",
 			mockedHTTPStatusCode: existingPackageStatus,
 		},
+		{
+			name: "Retrieving none existing non-crate-test from the mocked private registry",
```
Comment (lemeurherve) [inline pkg/plugins/resources/cargopackage/condition_test.go:145]:
```suggestion
			name: "Retrieving non existing non-crate-test from the mocked private registry",
```

File: pkg/plugins/resources/cargopackage/source_test.go [hunk 6]
```diff
@@ -58,6 +58,20 @@ func TestSource(t *testing.T) {
 			expectedResult: "0.1.0",
 			expectedError:  false,
 		},
+		{
+			name: "Passing case of retrieving none existing crate-test from the filesystem index",
```
Comment (lemeurherve) [inline pkg/plugins/resources/cargopackage/source_test.go:62]:
```suggestion
			name: "Passing case of retrieving non existing crate-test from the filesystem index",
```

Comment (loispostula) [reply pkg/plugins/resources/cargopackage/source_test.go:62]: That's hot it was and it failed the spelling check

File: pkg/plugins/resources/cargopackage/condition_test.go (hunk 4 above)
Comment (olblak) [reply pkg/plugins/resources/cargopackage/condition_test.go:65]: I made the revert suggestion :D 
The type check action is not happy with "non existing"

File: pkg/plugins/resources/cargopackage/source_test.go (hunk 6 above)
Comment (loispostula) [reply pkg/plugins/resources/cargopackage/source_test.go:62]: I'll update in a jiffy

**Review by olblak — APPROVED** [review]
I faced the same condition problem for other plugin.
I don't reminder if it is unified but I think it is the right approach
