### PR TITLE
fix(pullrequests) Do not mention a pull request in dry run when there are no changes

### LINKED ISSUE #484: Pull request are part of logs in dry run even if there is no change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing [the manifest for jenkins-lts](https://github.com/jenkins-infra/charts/blob/b2dc96519bfc490288a8f3cc8f5f2b3ead1e28ba/updatecli/updatecli.d/docker-images/jenkins-lts.yaml), when running locally updatecli with `updatecli diff --values ./updatecli/values.yaml --config ./updatecli/updatecli.d/docker-images/jenkins-lts.yaml`, it indicates us in its logs that a pull request is expected, while there is no change detected.

<details>
<summary>Logs</summary>

<pre>
#########################################
# BUMP JENKINS LTS DOCKER IMAGE VERSION #
#########################################

SOURCES
=======

latestRelease
-------------
Searching for version matching pattern "latest"
✔ Github Release version "0.12.8-2.319.2" found matching pattern "latest"

CHANGELOG:
----------

Release published on the 2022-01-21 08:16:14 +0000 UTC at the url https://github.com/jenkins-infra/docker-jenkins-lts/releases/tag/0.12.8-2.319.2

* chore(deps): update plugins (#403) @jenkins-infrastructure-admin

CONDITIONS:
===========

checkDockerImagePublished
-------------------------
WARNING: No architecture specified for the image "registry-1.docker.io/jenkinsciinfra/jenkins-lts:". Using the default "amd64".
✔ The Docker image registry-1.docker.io/jenkinsciinfra/jenkins-lts:0.12.8-2.319.2 exists and is available.

TARGETS
========

updateReleaseInConfig
---------------------

**Dry Run enabled**

✔ Key 'controller.tag', from file '/var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/kubernetes-management/config/ext_jenkins-release.yaml', already set to 0.12.8-2.319.2, nothing else need to be done

PULL REQUESTS
=============

[Dry Run] A Pull Request is expected (with kind "github" and title "[updatecli] Bump Jenkins LTS docker image version").

=============================

REPORTS:

✔ JENKINS-LTS.YAML:
        Sources:
                ✔ [latestRelease] Get latest jenkins-lts version(githubRelease)
        Condition:
                ✔ [checkDockerImagePublished] Test jenkinsciinfra/jenkins-lts:<latest_version> docker image tag(dockerImage)
        Target:
                ✔ [updateReleaseInConfig]  Update jenkinsciinfra/jenkins-lts docker image tag(yaml)

Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
</pre>

</details>

### Expected Behavior

No pull request should be expected, even in the logs.

### Steps To Reproduce

See above.

### Environment

```markdown
- OS: macOS
- updatecli: 0.18.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by olblak**
# An expected pull request is mentioned in dry run logs even if there is no change
Fix #484 

In the current state, this PR fix two bugs which by the way could be split into two Pull requests :) 

1. In Dry mode, don't mention that a PR will be open if it's not the case (#484 )
2. Pull request object correctly using the updated configuration. This avoids open pull requests with a message containing templating instruction such as `Bump app to {{ source "source" }}`

## Test

To test this pull request, you can run the following commands:
1. Run updatecli in dry mode and debug enable, with a updatecli configuration that shouldn't open a pullrequest. We shouldn't have pull request message
2. Run updatecli in dry mode and debug enable, with a updatecli configuration that should open a pull request and where the title contains templating instruction. We should have pull request message with the correct title

### Potential improvement

While working on this PR, I realize that we have confusion about what a pull request title should be. The title should be configured in the spec level and not at the pull request level.

```
pullrequestID:
  kind: github
  title: my title
  spec:
     label: 
        - dependencies
```

or 

```
pullrequestID:
  kind: github
  spec:
    title: my title 
    label: 
        - dependencies
```
At the moment the latter example, is implement in the code in a way that it's totally useless. 
I also realize that the way to generate a pullrequest title is overly complicated and could drastically simplified by just having the two following cases
1 A title is specified in the spec, then we use that value
2. No title specified so we let GitHub should, which will be the first commit title

### CODE REVIEW

File: pkg/core/pipeline/pullRequests.go [hunk 1]
```diff
@@ -103,13 +106,15 @@ func (p *Pipeline) RunPullRequests() error {
...
 		if p.Options.Target.DryRun {
-			logrus.Infof("[Dry Run] A Pull Request is expected (with kind %q and title %q).", pr.Config.Kind, pr.Title)
-
-			pullRequestDebugOutput := fmt.Sprintf("The expected Pull Request would have the following informations:\n\n##Title:\n%s\n\n##Changelog:\n\n%s\n\n##Report:\n\n%s\n\n=====\n",
-				pr.Title,
-				pr.Changelog,
-				pr.PipelineReport)
-			logrus.Debugf(strings.ReplaceAll(pullRequestDebugOutput, "\n", "\n\t|\t"))
+			if len(attentionTargetIDs) > 0 {
+				logrus.Infof("[Dry Run] A Pull Request is expected (with kind %q and title %q).", pr.Config.Kind, pr.Title)
```
Comment (lemeurherve) [inline pkg/core/pipeline/pullRequests.go:110]:
```suggestion
				logrus.Infof("[Dry Run] A pull request with kind %q and title %q is expected.", pr.Config.Kind, pr.Title)
```

File: pkg/core/pipeline/pullRequests.go [hunk 2]
```diff
@@ -103,13 +106,15 @@ func (p *Pipeline) RunPullRequests() error {
...
+
+				pullRequestDebugOutput := fmt.Sprintf("The expected Pull Request would have the following informations:\n\n##Title:\n%s\n\n##Changelog:\n\n%s\n\n##Report:\n\n%s\n\n=====\n",
```
Comment (lemeurherve) [inline pkg/core/pipeline/pullRequests.go:112]:
```suggestion
				pullRequestDebugOutput := fmt.Sprintf("The expected pull request would have the following informations:\n\n##Title:\n%s\n\n##Changelog:\n\n%s\n\n##Report:\n\n%s\n\n=====\n",
```

File: pkg/core/pipeline/pullrequest/main.go [hunk 3]
```diff
@@ -70,7 +70,7 @@ func New(config *Config, sourceControlManager *scm.Scm) (PullRequest, error) {
 
 	p := PullRequest{
 		Title:  config.Title,
-		Config: config,
+		Config: *config,
```
Comment (dduportal) [inline pkg/core/pipeline/pullrequest/main.go:73]: I'm wondering how this change could help? 

The type passed to the object was already a  `*Config`(e.g. a pointer) so the calling method on the `PullRequest` were already able to change its pointer reference.

Did I miss something?

**Comment by dduportal** [comment]
> At the moment the latter example, is implement in the code in a way that it's totally useless.
I also realize that the way to generate a pullrequest title is overly complicated and could drastically simplified by just having the two following cases
1 A title is specified in the spec, then we use that value
2. No title specified so we let GitHub should, which will be the first commit title

@olblak do you mind opening an issue describing this thought process and pointing some code elements? That would allow us to discuss the subject, reach a consensus and then implement it in async :)

File: pkg/core/pipeline/pullrequest/main.go (hunk 3 above)
Comment (olblak) [reply pkg/core/pipeline/pullrequest/main.go:73]: That was my understanding as well but it doesn't seem to work. I think that part would benefit from so refactoring. But I first needs to master the debugger :p

**Comment by olblak** [comment]
> @olblak do you mind opening an issue describing this thought process and pointing some code elements? That would allow us to discuss the subject, reach a consensus and then implement it in async :)

Yep, yep, which is why I mentioned it in "Potential Improvement" section

File: pkg/core/pipeline/pullrequest/main.go (hunk 3 above)
Comment (dduportal) [reply pkg/core/pipeline/pullrequest/main.go:73]: Given this consideration + the fact that the updatecli compiled from this PR stills creates PR with the litteral `{{ source ...}}`, do you mind removing this commit, so we can proceed on the rest of the code changes (eg fixing #484) ?


Many thanks for taking time for this!

Comment (dduportal) [reply pkg/core/pipeline/pullrequest/main.go:73]: For info, since this is only a "bugfix", I'm rebasing this PR to update it + remove the "PR title templating" tentative fix that would be a subsequent PR, so we can merge the initial fix.

**Review by dduportal — APPROVED** [review]
