### PR TITLE
fix(yaml) do not crash when the specified YAML array index does not exist

### LINKED ISSUE #439: If a key doesn't exists updatecli crashes
**Describe the bug**
Trying to check a key which doesn't exists in a condition results in the crash of updatecli.

**Steps to Reproduce**
For @dduportal:
https://github.com/jenkins-infra/kubernetes-management/pull/1881
In this PR I've trimmed [the podTemplate](https://github.com/jenkins-infra/kubernetes-management/blob/25fd5a8d4478b371c0e3b372247a890c35bd9d5c/PodTemplates.yaml) to keep only one container template, thus [this manifest](https://github.com/jenkins-infra/kubernetes-management/blob/7d62634660e13ec52171d70aedca316159b7becd/updatecli/updatecli.d/pod-templates/updatecli.yaml#L27) (and the yamllint too) references a key which doesn't exist anymore.

<details><summary>error log:</summary>

```

##############################

# BUMP UPDATECLI PODTEMPLATE #

##############################



SOURCES

=======


lastRelease

-----------

Searching for version matching pattern "latest"

✔ Github Release version "v0.17.2" found matching pattern "latest"



CHANGELOG:

----------


Release published on the 2022-01-03 09:30:04 +0000 UTC at the url https://github.com/updatecli/updatecli/releases/tag/v0.17.2


## Changes


## 🐛 Bug Fixes


- Bugfix: Don't try to open a pullrequest when not needed @olblak (#436)


## 🧰 Maintenance


- fix: correct regexp to retrieve last (non beta) go version @lemeurherve (#429)


## Contributors


@dduportal, @lemeurherve and @olblak




CONDITIONS:

===========


checkPodTemplate

----------------

panic: runtime error: index out of range [1] with length 1


goroutine 1 [running]:

github.com/updatecli/updatecli/pkg/plugins/yaml.replace(0xc0007474a0, {0xc00107a040, 0x2, 0x2}, {0xc000ddc740, 0x9}, 0x3)

	/home/runner/work/updatecli/updatecli/pkg/plugins/yaml/main.go:223 +0xa5c

github.com/updatecli/updatecli/pkg/plugins/yaml.replace(0xc000746be0, {0xc00107a030, 0x3, 0x3}, {0xc000ddc740, 0x9}, 0x1)

	/home/runner/work/updatecli/updatecli/pkg/plugins/yaml/main.go:274 +0x838

github.com/updatecli/updatecli/pkg/plugins/yaml.replace(0xc000746aa0, {0xc00107a030, 0x3, 0x3}, {0xc000ddc740, 0x9}, 0x1)

	/home/runner/work/updatecli/updatecli/pkg/plugins/yaml/main.go:274 +0x838

github.com/updatecli/updatecli/pkg/plugins/yaml.(*Yaml).condition(0xc0009b6ba0, {0x0, 0x0})

	/home/runner/work/updatecli/updatecli/pkg/plugins/yaml/condition.go:53 +0x1dd

github.com/updatecli/updatecli/pkg/plugins/yaml.(*Yaml).Condition(0xc0006d3878, {0x0, 0x40d047})

	/home/runner/work/updatecli/updatecli/pkg/plugins/yaml/condition.go:16 +0x1e

github.com/updatecli/updatecli/pkg/core/pipeline/condition.(*Condition).Run(0xc0006d3878, {0x0, 0x0})

	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/condition/main.go:108 +0x4bc

github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunConditions(0xc000a5c000)

	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/conditions.go:40 +0x49c

github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).Run(0xc000a5c000)

	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/main.go:210 +0x225

github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Run(0x3522ec0)

	/home/runner/work/updatecli/updatecli/pkg/core/engine/main.go:180 +0x594

github.com/updatecli/updatecli/cmd.run({0x1f54312, 0xc00013a500})

	/home/runner/work/updatecli/updatecli/cmd/root.go:100 +0x171

github.com/updatecli/updatecli/cmd.glob..func2(0x3505900, {0x1f54412, 0x4, 0x4})

	/home/runner/work/updatecli/updatecli/cmd/diff.go:27 +0xfd

github.com/spf13/cobra.(*Command).execute(0x3505900, {0xc00019c100, 0x4, 0x4})

	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8

github.com/spf13/cobra.(*Command).ExecuteC(0x3505e00)

	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc

github.com/spf13/cobra.(*Command).Execute(...)

	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902

github.com/updatecli/updatecli/cmd.Execute()

	/home/runner/work/updatecli/updatecli/cmd/root.go:40 +0x65

main.main()

	/home/runner/work/updatecli/updatecli/main.go:8 +0x17

script returned exit code 2

```

</details>

**Expected behavior**
There should be an error message, not a crash.

**Screenshots**

N/A

**Version**

- OS: Alpine image (jenkins/inbound-agent:4.11-1-alpine-jdk11)
- Updatecli version: v0.17.2

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by dduportal**
Fix #439

This was a quick one that fixes a real bug (a case on limit).

Thanks to the amount of unit tests that @olblak did on the homemade YAML parser, it was easy to add a failing case, and then fix it.

Now, the following error is thrown when an out of bounds index is specified for YAML arrays:

```
ERROR: ✗ cannot find key "spec.containers[1].name" in the YAML file ".tmp/PodTemplates.yaml"
```

## Test

To test this pull request, you can run the following commands:

```shell
$ make test-short # Fails without the fix on `pkg/plugins/yaml/main.go`
$ go build -o ./dist/updatecli && ./dist/updatecli diff --config ./.tmp/updatecli.yaml --values ~/workspace/jenkins-infra/kubernetes-management/updatecli/values.yaml
```

## Additional Information

- Also removed the "non cleaned" yaml file that was still commited (caught by @lemeurherve in his PR ❤️ ).
- Took the opportunity to switch the `Test_Replace()` to the `testify/assert` instructions

### CODE REVIEW

File: pkg/plugins/yaml/main_test.go [hunk 1]
```diff
@@ -207,11 +208,12 @@ func TestReplace(t *testing.T) {
 		key                []string
 		expectedOldVersion string
 		expectedValueFound bool
+		expectedError      bool
 	}
 
 	//https://github.com/go-yaml/yaml/issues/599
 
-	dataset := []dataSet{
+	dataset1 := []dataSet{
```
Comment (lemeurherve) [inline pkg/plugins/yaml/main_test.go:216]: Why the "1" suffix?

**Review by olblak — APPROVED** [review]

**Review by lemeurherve — APPROVED** [review]
