### PR TITLE
fix: truncate pull request body

### LINKED ISSUE #873: Github PullRequest body should be truncated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed multiple time that pullrequest created by Updatecli could failed if the body exceed maximum number of line authorized by GitHub.

The probably just have to truncated body [here](https://github.com/updatecli/updatecli/blob/main/pkg/plugins/scms/github/pullrequest.go#L221) 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- updatecli:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MusabShakeel576**
Fix #873 

Truncate long PR message to avoid `body is too long` error. 

## Test

To test this pull request, you can run the following commands:

```shell
go test -timeout 30s -run ^TestString$ github.com/updatecli/updatecli/pkg/plugins/utils/truncate
```

### Tradeoff

_No response_

### Potential improvement

_No response_

### CODE REVIEW

File: pkg/plugins/utils/truncate/main_test.go [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package truncate
+
+import (
+	"testing"
+)
+
+func TestString(t *testing.T) {
```
Comment (hervelemeur) [inline pkg/plugins/utils/truncate/main_test.go:7]: There should also be a test with a body too large.

File: pkg/plugins/utils/truncate/main.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+func String(str string, length int) string {
+	if length <= 0 {
+		return ""
+	}
+
+	if utf8.RuneCountInString(str) < length {
+		return str
+	}
+
+	return string([]rune(str)[:length])
```
Comment (hervelemeur) [inline pkg/plugins/utils/truncate/main.go:15]: I would add `...` at the end of the returned string to indicate it has been has been truncated.

File: pkg/plugins/scms/github/pullrequest.go [hunk 3]
```diff
@@ -218,7 +219,13 @@ func (p *PullRequest) generatePullRequestBody() (string, error) {
 		return "", err
 	}
 
-	return buffer.String(), nil
+	// GitHub Issues/PRs messages have a max size limit on the
+	// message body payload.
+	// `body is too long (maximum is 65536 characters)`.
+	// To avoid that, we ensure to cap the message to 60k chars.
+	const MAX_CHARACTERS_PER_MESSAGE = 60000
```
Comment (hervelemeur) [inline pkg/plugins/scms/github/pullrequest.go:226]:
```suggestion
	const MAX_CHARACTERS_PER_MESSAGE = 65000
```

**Comment by olblak** [comment]
Ho nice, it's great the way you handle it as we'll be able to use this truncate for gitea pullrequest and other scm coming

**Comment by olblak** [comment]
Ho nice, it's great the way you solved this as we'll be able to use this truncate for gitea pullrequest and other coming scm

File: pkg/plugins/utils/truncate/main.go (hunk 2 above)
Comment (olblak) [reply pkg/plugins/utils/truncate/main.go]: Indeed that could be an nice to have. 

So instead of "This line is too long", we would have "This line is too l..."

**Review by olblak — APPROVED** [review]
I already approve as the current the PR solve the initial. We have small nitpick suggestion.
I'll wait for the test to finish
