### PR TITLE
fix: report failure when at least one of the target is failing

### LINKED ISSUE #632: [updatecli 0.23.x] failing to open pull request + no error reported globally
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With updatecli 0.23.0 and 0.23.1, we have errors when trying to open a pull request, with the error `ERROR: 1 target(s) (updateChartVersion) failed for pullrequest "default"`.

Besides this failure, the execution of updatecli does NOT fail and does NOT report the failure, which makes it hard to detect.

### Expected Behavior

Can't be sure of the root cause error, but we have to fix updatecli so that, at least, it reports the failure, and eventually give details on the failure.

### Steps To Reproduce

* Any manifest at https://github.com/jenkins-infra/kubernetes-management/tree/56ff776b83f8677e16f8e8c9d422c7d3a7205a1f/updatecli/updatecli.d

  * In particular (a simple one):

```yaml
title: Bump aws-node-termination-handler helm chart version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://aws.github.io/eks-charts
      name: aws-node-termination-handler

targets:
  updateChartVersion:
    name: "eks/aws-node-termination-handler Helm Chart"
    kind: file
    scmid: default
    spec:
      file: clusters/cik8s.yaml
      matchpattern: 'chart: eks\/aws-node-termination-handler((\r\n|\r|\n)(\s+))version: .*'
      replacepattern: 'chart: eks/aws-node-termination-handler${1}version: {{ source "lastChartVersion" }}'

pullrequests:
  default:
    kind: github
    scmid: default
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - aws-node-termination
```

* Executing the diff works as expected and succeeds to report expected change + PR:

```shell
updatecli diff --values updatecli/values.yaml --config updatecli/updatecli.d/charts/aws-node-termination-handler.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/charts/aws-node-termination-handler.yaml"

SCM repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



########################################################
# BUMP AWS-NODE-TERMINATION-HANDLER HELM CHART VERSION #
########################################################


SOURCES
=======

lastChartVersion
----------------
✔ Helm Chart 'aws-node-termination-handler' version '0.18.1' is found from repository https://aws.github.io/eks-charts

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz




CHANGELOG:
----------

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz





TARGETS
========

updateChartVersion
------------------

**Dry Run enabled**

⚠ updated the [dry run] content of the file "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml"

--- /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
+++ /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
@@ -51,6 +51,6 @@
   - name: aws-node-termination-handler
     namespace: eks
     chart: eks/aws-node-termination-handler
-    version: 0.18.0
+    version: 0.18.1
     values:
       - "../config/ext_aws-node-termination-handler.yaml"



PULL REQUESTS
=============

[Dry Run] A pull request with kind "github" and title "[updatecli] Bump aws-node-termination-handler helm chart version" is expected.

=============================

REPORTS:


⚠ AWS-NODE-TERMINATION-HANDLER.YAML:
        Sources:
                ✔ [lastChartVersion]  (kind: helmChart)
        Target:
                ⚠ [updateChartVersion] eks/aws-node-termination-handler Helm Chart (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
 
```

* Applying the change fails at the Pull Request level, despite being reported as success:

```shell
updatecli apply --values updatecli/values.yaml --config updatecli/updatecli.d/charts/aws-node-termination-handler.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/charts/aws-node-termination-handler.yaml"

SCM repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



########################################################
# BUMP AWS-NODE-TERMINATION-HANDLER HELM CHART VERSION #
########################################################


SOURCES
=======

lastChartVersion
----------------
✔ Helm Chart 'aws-node-termination-handler' version '0.18.1' is found from repository https://aws.github.io/eks-charts

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz




CHANGELOG:
----------

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz





TARGETS
========

updateChartVersion
------------------
⚠ updated the content of the file "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml"

--- /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
+++ /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
@@ -51,6 +51,6 @@
   - name: aws-node-termination-handler
     namespace: eks
     chart: eks/aws-node-termination-handler
-    version: 0.18.0
+    version: 0.18.1
     values:
       - "../config/ext_aws-node-termination-handler.yaml"

no changed file to commit


PULL REQUESTS
=============

ERROR: 1 target(s) (updateChartVersion) failed for pullrequest "default"

=============================

REPORTS:


✔ AWS-NODE-TERMINATION-HANDLER.YAML:
        Sources:
                ✔ [lastChartVersion]  (kind: helmChart)
        Target:
                ✗ [updateChartVersion] eks/aws-node-termination-handler Helm Chart (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
```

### Environment

```markdown
- OS: macOS, Ubuntu 20.04
- updatecli: 0.23.0, 0.23.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lemeurherve**
# fix: report failure when at least one of the target is failing

Closes #632

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

### CODE REVIEW

**Review by dduportal — COMMENTED** [review]
LGTM but I defer to @olblak because it might break some use cases that we did not htink about.

File: pkg/core/pipeline/targets.go [hunk 1]
```diff
@@ -38,41 +36,27 @@ func (p *Pipeline) RunTargets() error {
...
-			p.Targets[id] = target
-			p.Report.Targets[id] = rpt
-			i++
-			continue
-		}
-
-		if strings.Compare(target.Result, result.ATTENTION) == 0 {
-			isResultIsChanged = true
+			p.Report.Result = result.FAILURE
+			return fmt.Errorf("Something went wrong in target \"%v\" :\n%v\n\n", id, err)
```
Comment (olblak) [inline pkg/core/pipeline/targets.go:46]:
```suggestion
			return fmt.Errorf("something went wrong in target \"%v\" :\n%v\n\n", id, err)
```
An error message shouldn't start with uppercase as it could be embedded in another error message

File: pkg/core/pipeline/targets.go [hunk 2]
```diff
@@ -38,41 +36,27 @@ func (p *Pipeline) RunTargets() error {
...
-
-			p.Targets[id] = target
-			p.Report.Targets[id] = rpt
-			i++
-			continue
-		}
-
-		if strings.Compare(target.Result, result.ATTENTION) == 0 {
-			isResultIsChanged = true
+			p.Report.Result = result.FAILURE
```
Comment (olblak) [inline pkg/core/pipeline/targets.go:45]: I didn't test it but I think, we also need to save the target state using 

```suggestion
			p.Report.Result = result.FAILURE
			p.Targets[id] = target
```

**Comment by olblak** [comment]
> LGTM but I defer to @olblak because it might break some use cases that we did not htink about.

If I remember correctly, the motivation to fail early after one failing target was to save some time (api call) but I think your suggestion improves the user experience as we see immediately what target is succeeding and those failing.

**Comment by dduportal** [comment]
> 

Correct ! Thanks for the memory. If I'm not mistaken, it was beforr you reworked the scm to have pullrequest/scm as top level: the proposal here makes sense now (while it was hard to implement before the rework).

File: pkg/core/pipeline/targets.go (hunk 2 above)
Comment (lemeurherve) [reply pkg/core/pipeline/targets.go:45]: `p.Targets[id]` already contains `target` here (AFAICT), as it's where it comes from (cf line 36), I don't think it should be reset. WDYT?

Comment (dduportal) [reply pkg/core/pipeline/targets.go:45]: These are 2 different objects, because of https://github.com/lemeurherve/updatecli/blob/is632-report-failure/pkg/core/pipeline/main.go#L26 which is not a pointer.

It means that https://github.com/updatecli/updatecli/pull/638/files#diff-de07e8be2bb72a5be95eaabc19216134364a70a5bf9a98c2903c41adb0477098R36 creates an entire different object into the variable `target` by copy.

Since this object is mutated later (https://github.com/updatecli/updatecli/pull/638/files#diff-de07e8be2bb72a5be95eaabc19216134364a70a5bf9a98c2903c41adb0477098R37, eventually during https://github.com/updatecli/updatecli/pull/638/files#diff-de07e8be2bb72a5be95eaabc19216134364a70a5bf9a98c2903c41adb0477098R43, etc.)
then you need to ensure that the pipeline is updated with the object at the end (otherwise the pullrequest would be executed with the original object, not the updated one).


Pleasures of low level languages :)

Comment (lemeurherve) [reply pkg/core/pipeline/targets.go:45]: Not sure if returning an updated but also failed target is really useful as we're returning an error. Added neverless.

**Review by olblak — APPROVED** [review]

**Review by dduportal — DISMISSED** [review]
LGTM (under the assumption that manual testing has to be done)

**Comment by olblak** [comment]
> LGTM (under the assumption that manual testing has to be done)

I'll do some test at the end of the day

**Review by olblak — CHANGES_REQUESTED** [review]
There is something fishy/
I tested this PR using 
```
targets:
  1:  
    kind: shell
    spec:
      command: "true"

  2:  
    kind: shell
    spec:
      command: "false"

  3:  
    kind: shell
    spec:
      command: "false"

  4:  
    kind: shell
    spec:
      command: "false"
```

and I got 
```
REPORTS:


✗ TEST.YAML:
	Sources:
	Target:
		✔ [1]  (kind: shell)
		- [2]  (kind: shell)
		- [3]  (kind: shell)
		- [4]  (kind: shell)
```
and I would expected 
```
REPORTS:


✗ TEST.YAML:
	Sources:
	Target:
		✔ [1]  (kind: shell)
		- [2]  (kind: shell)
		- [3]  (kind: shell)
		- [4]  (kind: shell)
```
where it stopped after one target failure

**Comment by olblak** [comment]
@lemeurherve I am opening a pullrequest on this one with a suggestion

**Comment by olblak** [comment]
Oops sorry I pushed directly to your branch :/, feel free to review my commit

**Comment by olblak** [comment]
With the manifest that I mention earlier, I get the following output

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "/tmp/test.yaml"

SCM repository retrieved: 0


++++++++++++
+ PIPELINE +
++++++++++++



#############
# TEST.YAML #
#############


TARGETS
========

4
-

**Dry Run enabled**

The shell 🐚 command "false" exited on error (exit code 1) with the following output:
----
----

command stderr output was:
----
----

3
-

**Dry Run enabled**

The shell 🐚 command "false" exited on error (exit code 1) with the following output:
----
----

command stderr output was:
----
----

2
-

**Dry Run enabled**

The shell 🐚 command "false" exited on error (exit code 1) with the following output:
----
----

command stderr output was:
----
----

1
-

**Dry Run enabled**

The shell 🐚 command "true" ran successfully with the following output:
----
----
No change detected

ERROR: something went wrong in target "4" : "Shell command exited on error."
ERROR: something went wrong in target "3" : "Shell command exited on error."
ERROR: something went wrong in target "2" : "Shell command exited on error."

Pipeline "TEST.YAML" failed
Skipping due to:
	"targets stage:\t\"something went wrong during target execution\""
targets stage:	"something went wrong during target execution"

=============================

REPORTS:


✗ TEST.YAML:
	Sources:
	Target:
		✔ [1]  (kind: shell)
		✗ [2]  (kind: shell)
		✗ [3]  (kind: shell)
		✗ [4]  (kind: shell)



Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	1
  * Skipped:	0
  * Succeeded:	0
  * Total:	1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed

```

**Comment by lemeurherve** [comment]
@olblak LGTM 😃

**Review by olblak — DISMISSED** [review]
I took the opportunity to fix minor issue

1. Always run all target no matter if an issue occur or not
2. fix small output issue

**Comment by olblak** [comment]
Please note that we don't handle the case where a target depends on another target which already failed

**Comment by olblak** [comment]
> Please note that we don't handle the case where a target depends on another target which already failed 
> I am wondering if it's something we want like for source 

I am planning to implement the missing depends on ccheck

**Comment by olblak** [comment]
```
title: Test Various target scenario

targets:
  1:  
    name: Should be succeeding
    kind: shell
    spec:
      command: "true"

  2:  
    name: Should be failling
    kind: shell
    spec:
      command: "false"

  3:  
    name: Should be failling
    kind: shell
    spec:
      command: "false"

  4:  
    name: Should be skipped
    depends_on:
      - 2 
    kind: shell
    spec:
      command: "false"

  5:  
    name: Should be succeeding
    kind: shell
    depends_on:
      - 1 
    spec:
      command: "true"

```

output 

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "e2e/updatecli.d/command.yaml"

SCM repository retrieved: 0


++++++++++++
+ PIPELINE +
++++++++++++



################################
# TEST VARIOUS TARGET SCENARIO #
################################


TARGETS
========

2
-

**Dry Run enabled**

The shell 🐚 command "false" exited on error (exit code 1) with the following output:
----
----

command stderr output was:
----
----

1
-

**Dry Run enabled**

The shell 🐚 command "true" ran successfully with the following output:
----
----
No change detected

4
-
WARNING: Parent target["2"] did not succeed. Skipping execution of the target["4"]

3
-

**Dry Run enabled**

The shell 🐚 command "false" exited on error (exit code 1) with the following output:
----
----

command stderr output was:
----
----

5
-

**Dry Run enabled**

The shell 🐚 command "true" ran successfully with the following output:
----
----
No change detected

ERROR: something went wrong in target "2" : "Shell command exited on error."
ERROR: something went wrong in target "3" : "Shell command exited on error."

Pipeline "Test Various target scenario" failed
Skipping due to:
	targets stage:	"something went wrong during target execution"

=============================

REPORTS:


✗ COMMAND.YAML:
	Sources:
	Target:
		✔ [1] Should be succeeding (kind: shell)
		✗ [2] Should be failling (kind: shell)
		✗ [3] Should be failling (kind: shell)
		- [4] Should be skipped (kind: shell)
		✔ [5] Should be succeeding (kind: shell)



Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	1
  * Skipped:	0
  * Succeeded:	0
  * Total:	1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed
[1]    18856 exit 1     ./bin/updatecli diff --config e2e/updatecli.d/command.yaml

```

**Review by olblak — APPROVED** [review]

File: pkg/core/pipeline/targets.go [hunk 3]
```diff
@@ -48,7 +48,20 @@ func (p *Pipeline) RunTargets() error {
...
+				logrus.Warningf("Parent target[%q] did not succeed. Skipping execution of the target[%q]", parentTarget, id)
+				shouldRunTarget = false
+				target.Result = result.SKIPPED
+				break
+			}
+		}
+
+		if shouldRunTarget {
+			err = target.Run(p.Sources[target.Config.SourceID].Output, &p.Options.Target)
+		}
```
Comment (lemeurherve) [inline pkg/core/pipeline/targets.go:64]: WDYT about not doing anything else if shoudlRunTarget is false?

Comment (olblak) [reply pkg/core/pipeline/targets.go:68]: Done :)

**Review by olblak — APPROVED** [review]

**Comment by olblak** [comment]
I am waiting for a final approval before merging this PR

**Comment by olblak** [comment]
After some test, I didn't catch any regression

**Comment by olblak** [comment]
Thanks @lemeurherve
