### PR TITLE
fix: Accessing yaml keys with . in the name fails

### LINKED ISSUE #904: Accessing yaml keys with `.` in the name fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would like to be able to access a `key` in a `yaml` target that contains periods - i.e. 
```
key: "spec.values.labels.service.istio.io/canonical-revision"
```
but this throws an error:
```
ERROR: something went wrong in target "helm-chart-label" : "✗ cannot find key 'spec.values.labels.service.istio.io/canonical-revision' from file 'gateway.yaml'"
```

I tried several other options trying to escape the periods but nothing seems to work:
```
"spec.values.labels.service.istio.io/canonical-revision"
"spec.values.labels.'service.istio.io/canonical-revision'"
"spec.values.labels.service\.istio\.io/canonical-revision"
```

### Expected Behavior

I should be able to pass label names or other strings to the yaml key 

### Steps To Reproduce

updatecli manifest file
```
targets:
  helm-chart-label:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: "gateway.yaml"
      key: "spec.values.labels.service.istio.io/canonical-revision"
    sourceid: gateway
```
gateway.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
spec:
  values:
    labels:
      service.istio.io/canonical-revision: "1.15.0"
```

### Environment

```markdown
- OS: 12.3.1
- updatecli: v0.34.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by olblak**
Signed-off-by: Olblak <me@olblak.com>

Fix #904 

Allow to escape `.` using `\` by adding YAML key parser

## Test

To test this pull request, you can run the following commands:

```shell
cp pkg/plugins/resources/yaml/
go test
```

### Potential improvement

While this pull-request fixes an issue in a local optimum, I am currently evaluating the missing parts to switch to https://github.com/tomwright/dasel for yaml file similar to json/toml/csv

### CODE REVIEW

File: pkg/plugins/resources/yaml/utils.go [hunk 1]
```diff
@@ -16,3 +17,39 @@ func joinPathWithWorkingDirectoryPath(filePath, workingDir string) string {
...
 }
+
+func parseKey(key string) []string {
+
+	elements := []string{}
+	element := ""
+	escapedCharacter := false
+
+	for i := range key {
+		fmt.Printf("Current element: %q\n", element)
```
Comment (olblak) [inline pkg/plugins/resources/yaml/utils.go:28]: To remove :/

**Comment by olblak** [comment]
https://github.com/updatecli/website/pull/527
