### PR TITLE
fix(pullrequest) show the correct report for the pull request section

### LINKED ISSUE #421: Wrong pullrequest message
**Describe the bug**
If we run `updatecli diff` the pullrequest message say "Nothing left to do as no target related to pullrequest "helm-charts" have changed" even if changed are needed 

**Steps to Reproduce**

**Expected behavior**

It should display what would happen

**Screenshots**
```
TARGETS
========

helm-chartss
------------

**Dry Run enabled**

INFO: Using spec.Value instead of source input value.
⚠ Key 'image.epinio.tag', from file '/tmp/updatecli/epinio/helm-charts/chart/epinio/values.yaml', was updated from '' to 'v0.3.1'


PULL REQUESTS
=============

Nothing left to do as no target related to pullrequest "helm-charts" has changed

=============================

REPORTS:


⚠ EPINIO.YAML:
	Sources:
		✔ [epinio] Get Latest epinio version(githubRelease)
	Condition:
		✔ [dockerImage] Check that splatform/epinio-installer:{{ source "epinio" }} is published(dockerImage)
		✔ [dockerImageContainer] Check that splatform/epinio-installer is used in Helm chart epinio(yaml)
	Target:
		⚠ [helm-chartss]  Update epinio version in chart epinio(helmChart)

```

**Version**

- OS: Linux
- Updatecli version: 0.17.0

**Additional context**
/

### PR DESCRIPTION
**Pull request by dduportal**
- Print a message by default when the dry run is used (and keep the debug detailed output)
- Do no print "Nothing left <...>" and proceed to opening/update Pull Requests when
  the targets reports "succeeded" (e.g. not changed). Closes #421
- Fix a typo on GitHub Pull Request log output

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
Co-authored-by: Olblak <me@olblak.com>

Fix #421 

With https://github.com/dduportal/docker-builder/blob/main/updatecli/updatecli.d/ghcli.yml

* Result in "diff" mode:

```
PULL REQUESTS
=============

[Dry Run] A Pull Request is expected (with kind "github" and title "[updatecli] Bump ghcli version").
```

* Result in "diff" mode with debug:

```
PULL REQUESTS
=============

[Dry Run] A Pull Request is expected (with kind "github" and title "[updatecli] Bump ghcli version").
DEBUG: The expected Pull Request would have the following informations:
        |
        |       ##Title:
        |       [updatecli] Bump ghcli version
        |
        |       ##Changelog:
        |
        |
        |       Release published on the 2021-12-02 18:04:53 +0000 UTC at the url https://github.com/cli/cli/releases/tag/v2.3.0
...
```

### CODE REVIEW

File: pkg/core/pipeline/pullRequests.go [hunk 1]
```diff
@@ -74,12 +74,6 @@ func (p *Pipeline) RunPullRequests() error {
 
 		failedTargetIDs, attentionTargetIDs, successTargetIDs, skippedTargetIDs := p.GetTargetsIDByResult(pr.Config.Targets)
```
Comment (olblak) [inline pkg/core/pipeline/pullRequests.go:75]:
```suggestion
		failedTargetIDs, _, successTargetIDs, skippedTargetIDs := p.GetTargetsIDByResult(pr.Config.Targets)
```
Is `attentionTargetIDs` still needed if we remove it in the next section?

Comment (dduportal) [reply pkg/core/pipeline/pullRequests.go:75]: Yes, it is needed in https://github.com/updatecli/updatecli/pull/427/files#diff-1f1229b2326f3c175da892cc978cc23d3c23bdf7485c59328b6fabc7288e65b1R89 for the loop that retrieves the changelogs.

Don't worry, this kind of situation (e.g. "variable not used") is always caught by both the linter and the compiler :)

Comment (olblak) [reply pkg/core/pipeline/pullRequests.go:75]: In fact this change should have been in https://github.com/updatecli/updatecli/pull/426/files

Comment (dduportal) [reply pkg/core/pipeline/pullRequests.go:75]: Not really, because #425 took care of this and was merged first

**Review by olblak — APPROVED** [review]
:shipit:
